spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:32770/koltin_spring_boot
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
